### ISSUE TITLE
Criar apelidos para métodos de Validação em pt_br

### ISSUE THREAD

**Issue by marcobraghim** [braghimsistemas/suitup-php#7]
Alguns dos métodos de validação foram escritos em portugues, vamos criar um alias para eles serem chamados por seu respectivo nome em ingles.

**Comment by braghimsistemas** [comment]
We will create a pull request to add unit tests to these validators first, so we can update these changes with tests and avoid problems.

**Comment by braghimsistemas** [comment]
Resolved on pull request #10
