### ISSUE TITLE
Criar apelidos para métodos de Filtros em pt_br

### ISSUE THREAD

**Issue by marcobraghim** [braghimsistemas/suitup-php#8]
Alguns dos métodos de **filtro** foram escritos em português, vamos criar um alias para eles serem chamados por seu respectivo nome em inglês.

**Comment by braghimsistemas** [comment]
We will create a pull request to add unit tests to these filters first, so we can update these changes with tests and avoid problems.

**Comment by braghimsistemas** [comment]
Resolved on pull request #10
